### ISSUE TITLE
So you want to be considered by T-libs?

### ISSUE THREAD

**Issue by workingjubilee** [EricLBuehler/trc#10]
Before it is worth putting in the queue for review:

1. This crate must pass miri. Ideally it would also pass miri with the following flags:
- [x] #12
- [x] #13
- [x] #14

2. This crate must be sound against all the correctness errors we have encountered in Arc and Rc and solved:

- [x] https://github.com/rust-lang/rust/issues/108706
- [x] https://github.com/rust-lang/rust/issues/95334
- [x] https://github.com/rust-lang/rust/issues/55005
- [x] https://github.com/rust-lang/rust/issues/51780
- [x] https://github.com/rust-lang/rust/issues/80365
- [x] https://github.com/rust-lang/rust/issues/30031
- [x] https://github.com/rust-lang/rust/issues/54908

3. In addition you must validate that it remains sound *and* fast even when used on "weak memory model" platforms. PowerISA (aka POWER aka PowerPC) is the weakest I know of for modern CPUs, but in a pinch, testing on AArch64 should flush out most problems, and is more important because we support aarch64-unknown-linux-gnu as a tier 1 platform. That makes its soundness in implementation of consequently higher concern, though we do take correctness seriously for tier 2 platforms, we're just humans with priorities.

4. Finally, and this is the most subjective evaluation: There has to be a reason to actually include it in std instead of just leaving it as an external crate. It's not good enough for it to simply be faster in a few cases. We often reject new API simply if it is too confusing or niche to choose when to use it.

**Comment by workingjubilee** [comment]
Prior verification efforts of the Rust standard library of interest:
- RustBelt: Securing the Foundations of the Rust Programming Language. https://plv.mpi-sws.org/rustbelt/popl18/
- RustBelt meets relaxed memory. https://doi.org/10.1145/3371102
- Tackling Real-Life Relaxed Concurrency with FSL++. https://plv.mpi-sws.org/fsl/ARC/paper.pdf
- Tree Borrows: A New Aliasing Model for Rust. https://perso.crans.org/vanille/treebor/

...uh, you most certainly do not need to read all of these or anything, you just might find them informative since they discuss correctness and incorrectness of Rust code, and especially unsafe Rust code, extensively. The last is most novel and also most unproven but at the same time is the Rust model of operational semantics being experimented with after a hell of a lot of experimentation.

**Comment by EricLBuehler** [comment]
@workingjubilee, thank you for sending me those! I will be sure to check them out.

**Comment by EricLBuehler** [comment]
Regarding point 3, I own a Raspberry Pi 4 (has the armv8a that is a superset of aarch64  -https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/), which has an aarch64 architecture. Would soundness on this machine be an adequate check?

**Comment by workingjubilee** [comment]
It would be a useful start, at least. One of the things about the RPi that makes it not quite the same as say, an M1, is that it doesn't run a very deep pipeline with hundreds of instructions in flight, so there's no huge stalls that might trash performance in the worst case scenario. But also, it's still interesting, because the RPi lacks a straightforward implementation of `compare_exchange`, and instead uses atomic instructions that operate like `compare_exchange_weak`.

**Comment by EricLBuehler** [comment]
Yes, I hope that would be sufficent as I do not have access to, for example, and M1. The only ARM devices I have are my RPis.

Like you said, hopefully this benchmark with the RPi will provide some contrast to more powerful and complex processors.

**Comment by workingjubilee** [comment]
I have a diverse array of CPUs, including some _very_ exotic architectures that Rust supports, and I will be happy to run some benchmarks on my machines once you've done some initial testing.

Including an M1.

**Comment by EricLBuehler** [comment]
Thank you for the offer! I would really appreciate it - perhaps after #9 is closed. Maybe you can submit the results via pull request? Again, thank you!

**Comment by EricLBuehler** [comment]
I believe that point 3 has been resolved - See [this](../blob/master/BENCHMARKS.md) new benchmark file which includes a benchmark on an AArch63 platform.

**Comment by hoxxep** [comment]
Regarding (3), benchmark results on an M1 machine show similar performance improvements. I can make a PR to include these into `BENCHMARKS.md` if helpful.

```     
Running benches/benchmark.rs (target/release/deps/benchmark-dcc1722be38d6f11)

Clone Trc               time:   [29.543 ns 29.583 ns 29.630 ns]
Clone Arc               time:   [19.866 ns 19.898 ns 19.939 ns]
Clone Rc                time:   [16.147 ns 16.167 ns 16.192 ns]

Multiple clone Trc      time:   [439.11 ns 439.65 ns 440.27 ns]
Multiple clone Arc      time:   [968.11 ns 969.31 ns 970.65 ns]
Multiple clone Rc       time:   [409.21 ns 409.79 ns 410.41 ns]

Deref Trc               time:   [16.216 ns 16.234 ns 16.254 ns]
Deref Arc               time:   [16.603 ns 16.658 ns 16.732 ns]
Deref Rc                time:   [15.510 ns 15.527 ns 15.546 ns]

Multiple deref Trc      time:   [48.608 ns 48.942 ns 49.274 ns]
Multiple deref Arc      time:   [48.444 ns 48.821 ns 49.214 ns]
Multiple deref Rc       time:   [46.125 ns 46.199 ns 46.293 ns]

Multiple threads Trc    time:   [1.6919 ms 1.7013 ms 1.7121 ms]
Multiple threads Arc    time:   [2.6750 ms 2.6922 ms 2.7177 ms]

Multiple threads Trc Medium
                        time:   [1.9873 ms 1.9988 ms 2.0110 ms]
Multiple threads Arc Medium
                        time:   [6.4657 ms 6.4865 ms 6.5094 ms]

Multiple threads Trc Long
                        time:   [8.1004 ms 8.1267 ms 8.1547 ms]
Multiple threads Arc Long
                        time:   [97.849 ms 97.950 ms 98.056 ms]

Multiple threads Trc Super
                        time:   [34.427 ms 34.517 ms 34.609 ms]
Multiple threads Arc Super
                        time:   [476.58 ms 476.73 ms 476.88 ms]
```

**Comment by EricLBuehler** [comment]
Point 10 is NA because I directly allocate an array of `T`.

**Comment by EricLBuehler** [comment]
Point 8 is also NA because of my handling of dangling `Weak`s.

**Comment by EricLBuehler** [comment]
Point 6 is not a problem for `Trc` because if the `sharedref` goes to 0, then we are guaranteed to be the only ones holding a reference to `SharedTrcInternal`.

**Comment by EricLBuehler** [comment]
Point 7 is resolved because we have an `Acquire` to establish the required happens-before relationship.

**Comment by EricLBuehler** [comment]
Regarding section/point 4 (API nicheness), I believe that Trc's usefulness comes from it's **major** performance gains, as can be seen in the benchmarks. However, because Trc is currently outside of the `std` library, `CoerceUnsized`, and `Receiver` cannot be implemented.

Regarding `DispatchFromDyn`, the following from [here](https://doc.rust-lang.org/std/ops/trait.DispatchFromDyn.html) pertains:
>Other than one-aligned, zero-sized fields, the definition for Self must have exactly one field and that field’s type must be the coerced type. Furthermore, Self’s field type must implement DispatchFromDyn<F> where F is the type of T’s field type.
Because the design of `Trc` means that each instance of the struct has a localcount and a sharedcount, 2 fields are present in the `Trc` struct. Of course, this could be implemented for the `SharedTrc` struct that is essentially `Arc`.

@workingjubilee, I would appreciate your thoughts on this, particularly regarding any workarounds I can use to implement `DispatchFromDyn` for `Trc` itself.
