### ISSUE TITLE
Benchmarks shouldn't use `Instant::now()` in a loop

### ISSUE THREAD

**Issue by reinerp** [EricLBuehler/trc#2]
I see your benchmarks call `Instant::now()` in the inner loop. That timing function takes _much_ longer than the deref operation being benchmarked, so what you end up benchmarking is how fast you can read the clock, rather than how fast you can deref.

https://github.com/EricLBuehler/trc/blob/56c73e560fd6ccf4667149f80b56f83e773f3dff/src/main.rs#L67

A better approach is to hoist the timing outside the loop, so you only call the clock once per 100000 iterations. You should also use `std::hint::black_box` to ensure that computations don't get hoisted outside the loop or eliminated by the compiler. So, a better benchmark would be:

```
fn test_deref_rc() -> f64{
    let rc = Rc::new(100);
    
    let start = Instant::now();
    for _ in 0..100000 {
        std::hint::black_box(*std::hint::black_box(rc));
    }
    let end = Instant::now();
    (end-start).as_nanos() as f64 / 100000.
}
```

**Comment by EricLBuehler** [comment]
Thanks you! It sounds great - I will add that shortly.
