### ISSUE TITLE
Switch to Criterion for benchmarking

### ISSUE THREAD

**Issue by sigaloid** [EricLBuehler/trc#4]
Hi, a better way to measure benchmarks would be to use the [Criterion](https://lib.rs/crates/criterion) crate as it abstracts over a lot of the hard-to-get-right benchmarking code. I can send a PR if you'd like!

**Comment by EricLBuehler** [comment]
Yes, please, that would be great if you can! I could not really find how to do it.

**Comment by EricLBuehler** [comment]
Looks great! Thank you so much.
